const NOTIFICATION_ACTION_TYPES = {
    ADD_NEW_LIKE_NOTIFICATION: "notification/ADD_NEW_LIKE_NOTIFICATION",
    MARK_AS_SEEN_LIKE_NOTIFICATIONS_START: "notification/MARK_AS_SEEN_LIKE_NOTIFICATIONS_START",
    MARK_AS_SEEN_LIKE_NOTIFICATIONS_SUCCESS: "notification/MARK_AS_SEEN_LIKE_NOTIFICATIONS_SUCCESS",
    MARK_AS_SEEN_LIKE_NOTIFICATIONS_FAILED: "notification/MARK_AS_SEEN_LIKE_NOTIFICATIONS_FAILED",
}

export default NOTIFICATION_ACTION_TYPES;