const NOTIFICATION_ACTION_TYPES = {
    ADD_NEW_NOTIFICATION: "notification/ADD_NEW_NOTIFICATION",
    MARK_AS_SEEN_NOTIFICATIONS_START: "notification/MARK_AS_SEEN_NOTIFICATIONS_START",
    MARK_AS_SEEN_NOTIFICATIONS_SUCCESS: "notification/MARK_AS_SEEN_NOTIFICATIONS_SUCCESS",
    MARK_AS_SEEN_NOTIFICATIONS_FAILED: "notification/MARK_AS_SEEN_NOTIFICATIONS_FAILED",
    FETCH_OFFLINE_UNSEEN_NOTIFICATIONS_START: "notification/FETCH_OFFLINE_UNSEEN_NOTIFICATIONS_START",
    FETCH_OFFLINE_UNSEEN_NOTIFICATIONS_SUCCESS: "notification/FETCH_OFFLINE_UNSEEN_NOTIFICATIONS_SUCCESS",
    FETCH_OFFLINE_UNSEEN_NOTIFICATIONS_FAILED: "notification/FETCH_OFFLINE_UNSEEN_NOTIFICATIONS_FAILED",
    FETCH_SEEN_NOTIFICATIONS_START: "notification/FETCH_SEEN_NOTIFICATIONS_START",
    FETCH_SEEN_NOTIFICATIONS_SUCCESS: "notification/FETCH_SEEN_NOTIFICATIONS_SUCCESS",
    FETCH_SEEN_NOTIFICATIONS_FAILED: "notification/FETCH_SEEN_NOTIFICATIONS_FAILED",
    CLEAR_UNSEEN_NOTIFICATION_FOR_VIEW: "notification/CLEAR_UNSEEN_NOTIFICATION_FOR_VIEW",
}

export default NOTIFICATION_ACTION_TYPES;