const SOCKET_ACTION_TYPES = {
    SOCKET_CONNECT: 'socket/SOCKET_CONNECT',
    SOCKET_DISCONNECT: 'socket/SOCKET_DISCONNECT',
    SET_SOCKET: 'socket/SET_SOCKET'
}

export default SOCKET_ACTION_TYPES;