const USER_ACTION_TYPES = {
    LOGIN_START: "user/LOGIN_START",
    LOGIN_SUCCESS: "user/LOGIN_SUCCESS",
    LOGIN_FAILED: "user/LOGIN_FAILED",
    SIGNUP_START: "user/SIGNUP_START",
    SIGNUP_SUCCESS: "user/SIGNUP_SUCCESS",
    SIGNUP_FAILED: "user/SIGNUP_FAILED",
    LOGOUT_START: "user/LOGOUT_START",
    LOGOUT_SUCCESS: "user/LOGOUT_SUCCESS",
    LOGOUT_FAILED: "user/LOGOUT_FAILED",
    FETCH_SUGGESTED_USERS_START: "user/FETCH_SUGGESTED_USERS_START",
    FETCH_SUGGESTED_USERS_SUCCESS: "user/FETCH_SUGGESTED_USERS_SUCCESS",
    FETCH_SUGGESTED_USERS_FAILED: "user/FETCH_SUGGESTED_USERS_FAILED",
}

export default USER_ACTION_TYPES;