const POST_ACTION_TYPES = {
    FETCH_FEED_POSTS_START: "post/FETCH_ALL_POSTS_START",
    FETCH_FEED_POSTS_SUCCESS: "post/FETCH_FEED_POSTS_SUCCESS",
    FETCH_FEED_POSTS_FAILED: "post/FETCH_FEED_POSTS_FAILED",
    EMPTY_FEED_POSTS: "post/EMPTY_FEED_POSTS",
}

export default POST_ACTION_TYPES;