const COMMENT_ACTION_TYPES = {
    CREATE_COMMENT_START: 'comment/CREATE_COMMENT_START',
    CREATE_COMMENT_SUCCESS: 'comment/CREATE_COMMENT_SUCCESS',
    CREATE_COMMENT_FAILED: 'comment/CREATE_COMMENT_FAILED',
    EDIT_COMMENT_START: 'comment/EDIT_COMMENT_START',
    EDIT_COMMENT_SUCCESS: 'comment/EDIT_COMMENT_SUCCESS',
    EDIT_COMMENT_FAILED: 'comment/EDIT_COMMENT_FAILED',
    
    DELETE_COMMENT_START: 'comment/DELETE_COMMENT_START',
    DELETE_COMMENT_SUCCESS: 'comment/DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILED: 'comment/DELETE_COMMENT_FAILED',
}

export default COMMENT_ACTION_TYPES;