const COMMENT_ACTION_TYPES = {
    CREATE_COMMENT_START: 'comment/CREATE_COMMENT_START',
    CREATE_COMMENT_SUCCESS: 'comment/CREATE_COMMENT_SUCCESS',
    CREATE_COMMENT_FAILED: 'comment/CREATE_COMMENT_FAILED',
    DELETE_COMMENT_START: 'comment/CREATE_COMMENT_START',
    DELETE_COMMENT_SUCCESS: 'comment/CREATE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILED: 'comment/CREATE_COMMENT_FAILED',
}

export default COMMENT_ACTION_TYPES;